name: ğŸš€ Deploy S&P500 Dashboard to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: â¬‡ï¸ Checkout code
      uses: actions/checkout@v3

    - name: ğŸ” Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: ğŸš€ Deploy to EC2
      run: |
        ssh -tt -o StrictHostKeyChecking=no deploy@13.42.17.17<< 'EOF'
          cd ~/SP500_Dashboard || mkdir -p ~/SP500_Dashboard && cd ~/SP500_Dashboard
          
          echo "â¬‡ï¸ Pulling latest code..."
          if [ -d ".git" ]; then
            git reset --hard
            git pull origin main
          else
            git clone https://github.com/VatsalSangani/S-P500_stock_forecasting_dashboard.git .
          fi
          
          echo "ğŸ§¹ Stopping and removing previous dashboard container..."
          docker stop sp500-app 2>/dev/null || true
          docker rm sp500-app 2>/dev/null || true
          
          echo "ğŸ§¹ Removing previous dashboard image..."
          docker rmi -f sp500-dashboard:latest 2>/dev/null || true
          
          echo "ğŸ“¦ Building new Docker image..."
          docker build -f Dockerfile -t sp500-dashboard:latest .
          
          echo "ğŸš€ Running new Docker container..."
          docker run -d -p 8502:8501 --name sp500-app \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_DEFAULT_REGION=eu-west-2 \
            sp500-dashboard:latest

          exit 0
        EOF
